call ant build
echo Pushing file...
call adb push c:\Dev\ws-android\OneButtonUiTest\bin\OneButtonUiTest.jar /data/local/tmp/
echo Running test...
call adb shell uiautomator runtest OneButtonUiTest.jar -c com.test.UIPushButtonTest