call ant build
echo Pushing file...
call adb push D:\Dev\Git\cbt-example-app-uiautomator\bin\OneButtonUiTest.jar /data/local/tmp/
echo Running test...
call adb shell uiautomator runtest OneButtonUiTest.jar -c com.test.TestButton1,com.test.TestButton2,com.test.TestButton3,com.test.TestButton4